version: "3"

services:
  # MySQL 5.7.x
  db:
    extends:
      file: ./docker-compose-common.yml
      service: default_base_service
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ro0tpass
      MYSQL_DATABASE:      homestead
      MYSQL_USER:          homestead
      MYSQL_PASSWORD:      secret
    volumes:
      - ./storage/database:/var/lib/mysql
      - ./storage/logs:/var/log/mysql

  # PHP-FPM 7.0.x
  php7:
    extends:
      file: ./docker-compose-common.yml
      service: default_base_service
    container_name: php7
    build: ./php7.0-fpm
    environment:
      DEBUG: 1
      SSH_AUTH_SOCK: /ssh-agent
    volumes:
      - $SSH_AUTH_SOCK:/ssh-agent # Forward SSH Agent to Docker container
      - ./php7.0-fpm/php.ini:/etc/php.ini
      - ./php7.0-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./storage/logs:/var/log/php-fpm
      - .:/app
    links:
      - db

  # Nginx 1.10.x
  web:
    extends:
      file: ./docker-compose-common.yml
      service: default_base_service
    container_name: web
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./storage/logs:/var/log/nginx
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
      - .:/app
    links:
      - php7
